name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: danlopz/metrics@master
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: danlopz
          repo: metrics
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: danlopz/metrics/projects/1
